# Example: https://github.com/rodrigokamada/angular-github-actions
# https://github.com/peaceiris/actions-gh-pages
name: CI Build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run coverage
        run: yarn coverage:ci

      - name: Build
        run: yarn build:ci

      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/drevo/browser
          enable_jekyll: true
